_target_: manner.models.baselines.caum_plm_module.CAUMPLMModule

# news encoder
plm_model: ""
frozen_layers: [0, 1, 2, 3, 4, 5, 6, 7]
dropout_probability: 0.2
text_embedding_dim: 768
num_attention_heads: 16
entity_num_attention_heads: 20
query_vector_dim: 200
category_embedding_dim: 100
use_entities: True

pretrained_entity_embeddings_path: ""
entity_embedding_dim: 100
news_out_embedding_dim: 400

# user encoder
num_filters: 400
dense_att_hidden_dim1: 400
dense_att_hidden_dim2: 256
user_vector_dim: 400

# evaluation
num_categ_classes: 19 # 18 + 1
num_sent_classes: 4 # 3 + 1

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.00001
