_target_: manner.models.baselines.lstur_plm_module.LSTURPLMModule

# news encoder
plm_model: ""
frozen_layers: [0, 1, 2, 3, 4, 5, 6, 7]
dropout_probability: 0.2
text_embedding_dim: 768
num_attention_heads: 16
query_vector_dim: 200
category_embedding_dim: 100

# user encoder
num_users: 643372 # 643371+ 1
user_masking_probability: 0.5
long_short_term_method: "ini" # ini, con

# evaluation
num_categ_classes: 19 # 18 + 1
num_sent_classes: 4 # 3 + 1

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.00001
