_target_: manner.models.baselines.senti_debias_plm_module.SentiDebiasPLMModule

# news encoder
plm_model: ""
frozen_layers: [0, 1, 2, 3, 4, 5, 6, 7]
dropout_probability: 0.2
text_embedding_dim: 768
num_attention_heads: 16
query_vector_dim: 200

# sentiment encoder
sent_embedding_dim: 256

# sentiment discriminator
sent_hidden_dim: 400

# loss coefficients
alpha_coefficient: 0.15 
beta_coefficient: 10

# evaluation
num_categ_classes: 19 # 18 + 1
num_sent_classes: 4 # 3 + 1

optimizer_generator:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.00001

optimizer_discriminator:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.00002
